services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn --bind 0.0.0.0:8000 app:app
    ports:
      - 8000:8000
    env_file: .env.prod
  nginx:
    image: "${NGINX_IMAGE}"
    ports:
      - 80:80
    depends_on:
      - web